### ISSUE TITLE
feat: must join before play

### ISSUE THREAD

**Issue by amangtele** [amanqs/AmangMusic#1]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [x] No

**Comment by amanqs** [comment]
mungkin minggu depan

**Comment by amangtele** [comment]
> mungkin minggu depan

mantap
